name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Run coverage
        run: mv app-bucket/config-example.json  app-bucket/config.json ; mv app-bucket/logins-example.json  app-bucket/logins.json ; go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
